Tests for auto-polygon
edozo/cypress_tests pull request #1
Opened 2020-11-24 16:45 UTC by martinmcneela

Ticket: https://edozohq.atlassian.net/browse/MAPS-896

Notes: I have added an extra scenario for when a user clicks and there is not inspire data, will pop that in the ticket too.
﻿

2020-11-25 10:42 UTC, zac-robinson requested changes

2020-11-25 10:42 UTC, zac-robinson commented on cypress/integration/Autopolygon/Autopolygon.js
> +When(`I go from {string} to {string}`, (freeLayer, paidLayer) => {
This step is duplicated from one in PurchaseMap. Can you move it into the common folder and have them both use the same one please?

2020-11-25 10:42 UTC, zac-robinson commented on cypress/integration/Autopolygon.feature
> +    @has-data
Do these annotations do anything specifically?

2020-11-25 10:42 UTC, zac-robinson commented on cypress/integration/Autopolygon.feature
> +    @has-not-data
```suggestion
    @has-no-data
```

2020-11-25 10:42 UTC, zac-robinson commented on cypress/integration/Autopolygon.feature
> +    Then Add the polygon to the map where data exists
I think this makes more sense being : Then The polygon is added to the map

2020-11-25 10:42 UTC, zac-robinson commented on cypress/integration/Autopolygon.feature
> +    Then Try to add the polygon to the map where no data exists
Similarly I think this one should be: Then The modal is shown and no polygon is added

2020-11-25 10:42 UTC, zac-robinson commented on cypress/integration/Autopolygon/Autopolygon.js
> +  cy.route("GET", `${Cypress.env("apiUrl")}/polygon?*`).as("getAutoPolygon");
I don't think you need the Cypress.env part

2020-11-25 10:42 UTC, zac-robinson commented on cypress/integration/Autopolygon/Autopolygon.js
> +And(`I click to select {string} tool`, () => {
Can this be moved to the common steps as well

2020-11-25 11:15 UTC, martinmcneela commented on cypress/integration/Autopolygon.feature
> +    @has-data
There is this https://github.com/TheBrainFamily/cypress-cucumber-example#tags-usage, but pretty sure I am not using them correctly so just removed them for now - was trying to make it easy to see what tests were on what scenario.

2020-11-25 14:38 UTC, zac-robinson approved these changes

2020-11-25 14:38 UTC, zac-robinson commented on cypress/integration/Autopolygon/Autopolygon.js
> + */
These comments can be removed

2020-11-25 14:38 UTC, zac-robinson commented on cypress/integration/Autopolygon/Autopolygon.js
> +When(`I click to select {string} tool`, () => {
I think I missed it last time, can this go into common please. We will need this in lots of places going forward

2020-11-25 15:40 UTC, martinmcneela commented on cypress/integration/Autopolygon/Autopolygon.js
> +When(`I click to select {string} tool`, () => {
Yeah I was thinking about that but didn't do it as the name of the tool will change and I couldn't get it to pull through the `{string}`

2020-11-25 16:13 UTC, martinmcneela commented on cypress/integration/Autopolygon/Autopolygon.js
> +When(`I click to select {string} tool`, () => {
Scratch that, got it to work but needs a small PR to the maps FE app first.

2020-11-26 10:34 UTC, zac-robinson requested changes
The tests failed

2020-11-26 11:32 UTC, zac-robinson approved these changes

2020-11-26 11:36 UTC, merged