Build/GitHub actions
edozo/cypress_tests pull request #10
Opened 2021-01-25 14:00 UTC by Hazz223

2021-01-26 14:30 UTC, zac-robinson requested changes

2021-01-26 14:30 UTC, zac-robinson commented on cypress/integration/EditMap/EditMap.js
>    });
Remove this

2021-01-26 14:30 UTC, zac-robinson commented on cypress.json
> +  "projectId": "mfymzy"
Is this random keyboard mashing or is it the id from dashboard?

2021-01-26 14:30 UTC, zac-robinson commented on cypress/support/helpers.js
> +const pollForMapReady = function pollForMapReady(mapId, token, loopNumer) {
loopNumber rather than loopNumber

2021-01-26 14:30 UTC, zac-robinson commented on cypress/support/helpers.js
> +};
```suggestion
export const stringRandomiser = (given) => `${given}-${Date.now()}`;
```

2021-01-26 14:30 UTC, zac-robinson commented on cypress/support/helpers.js
> +const pollForMapReady = function pollForMapReady(mapId, token, loopNumer) {
should be `export const pollForMapReady = (mapId, token, loopNumber) => {`

2021-01-26 14:30 UTC, zac-robinson commented on cypress/support/helpers.js
> +export { stringRandomiser as stringRandomiser, pollForMapReady as pollForMapReady };
Don't need this

2021-01-26 14:30 UTC, zac-robinson commented on cypress/integration/EditMap/EditMap.js
> +          });
```suggestion
          cy.get('@edozoJwt').then((token) => pollForMapReady(mapId, token, 0));
```

2021-01-26 14:30 UTC, zac-robinson commented on cypress/integration/EditMap/EditMap.js
> +    })
```suggestion
    .then((name) => cy.findByText(name))
```

2021-01-26 14:48 UTC, Hazz223 commented on cypress.json
> +  "projectId": "mfymzy"
That's the project ID. I'll leave this in here for now, and I'll move it to env vars once we've got multiple instances of this running, like on deploys of Data-Service etc. Sound good?

2021-01-26 14:58 UTC, zac-robinson submitted a review, later dismissed

2021-01-26 15:07 UTC, martinmcneela requested changes

2021-01-26 15:07 UTC, martinmcneela commented on cypress/support/commands.js
> +  cy.findByTestId('submit').click();
Does this need to be changed? Given we are able to find the correct elements with the placeholder text and role?

2021-01-26 15:07 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
> +        });
I know it isn't necessarily from now but the `And` blocks seem like they could be compressed into one, so rather than `I set the name to {string}` make it `I set the {string} to {string}` using the first sting to find the element (by placeholder or testid)

2021-01-26 15:09 UTC, Hazz223 commented on cypress/support/commands.js
> +  cy.findByTestId('submit').click();
I found the login box, bot locally and on GH, really hit and miss using the placeholder text. Since moving it to an ID it's not failed once. So would prefer to move it to this.

2021-01-26 15:10 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +        });
Can I submit this as a separate PR - I've got some ideas on how to solve the duplication that I've found.

2021-01-26 15:12 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
> +        });
100%, just wanted to not it that's all.

2021-01-26 15:21 UTC, martinmcneela commented on cypress/support/commands.js
> +  cy.findByTestId('submit').click();
In reality it is probably the `intercept` and `wait` that is making it more consistent, rather than the addition of the test id's. Just ran it a few times with placeholder and the intercept and also hasn't failed once.

2021-01-26 16:53 UTC, Hazz223 commented on cypress/support/commands.js
> +  cy.findByTestId('submit').click();
I'm not sure what to do here, as both methods work. 
I guess this boils down to: Are these visual regression tests, or are they functional? Does this test care the placeholder is "Email", or does it care about logging into the site. 
I'd argue Cypress is a functional test framework, [which pushes towards test-ids for each button / field / item of interest](https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements) to make it easy to hook in and interact with.
If we're interested that we've not changed the look of the site, we should look at visual regression testing our application.

2021-01-26 17:38 UTC, martinmcneela commented on cypress/support/commands.js
> +  cy.findByTestId('submit').click();
I get that they are not visual test but they are test in the traversal of the DOM (as a user would do it).

- Having test id's sets the precedent that this is how we find a thing in the DOM, when in reality it is possible (and easier given we don't have to add a special piece of code for it) to find it without having to add another complication into the FE code. Taking lessons from testing-library the order in which we should be targeting elements - https://testing-library.com/docs/queries/about/#priority
- I have seen data-testid described as an 'escape hatch', it should not be needed in 99% of cases. And if it is it means that the app is probably not accessible - the example that comes to mind it selecting a drawing tool because it is just an icon it needs a test id.

@zac-robinson do you ahve any imput on this one? I am happy enought to have them stay in for this PR but in reality I'd have chalanged the PR in maps if I'd seen it yesterday.

2021-01-27 08:53 UTC, Hazz223 commented on cypress/support/commands.js
> +  cy.findByTestId('submit').click();
Having read the article, I see what they mean around using the accessible name - as these should be possible for screen readers etc. Very on board for that, as it'll push us towards making elements more accessible. They should also be unique, and not cause confusion for Cypress. So in a way, they act as a more consistent identifier. I'm happy with that. Using a placeholder name is not the same, and is apparently discouraged [an accessibility stand point](https://govuk-elements.herokuapp.com/form-elements/#form-focus-states). 

I'm happy to change the usage here towards names instead.

2021-01-27 09:17 UTC, martinmcneela commented on cypress/support/commands.js
> +  cy.findByTestId('submit').click();
Fair point name is probably a fair way to target it. 

In reallity we should have text labels for all of our inputs, would make it even easier. I can't believe i'm about to say this but our inpus should probably follow what the government are doing 😅, all the UX debt that we have never got to either. But what they are refering to there as a placeholder could also been seen by a lot of people as additional information (what would have beeen a little `i` icon or a tooltip on older government sites). This is also what is referenced is someones direction on thier own style guide no necessarily a best prctice in the indutry.

But in reality if the placeholder exists in our app it is still a valid way to target an item as they will not be changing very much.

2021-01-27 10:30 UTC, martinmcneela approved these changes

2021-01-27 11:40 UTC, zac-robinson approved these changes

2021-01-27 11:54 UTC, merged