MAPS-898: add scenario 3
edozo/cypress_tests pull request #3
Opened 2020-12-03 15:45 UTC by wiled

Note: the map layer for street is currently "street" and not "street
map" in stage.

2020-12-08 11:05 UTC, zac-robinson commented on cypress/integration/AutomatedAreaTextBox.feature
> +    And I create a text box with the text 'Hello Wembley'
I think the automated text box is the "Add area to polygon" button in the top right corner when a polygon is selected. This scenario is still valid but worth correcting the name and adding this scenario into the BDD doc

2020-12-08 12:20 UTC, martinmcneela requested changes
@wiled I have added a few comments some are just text tweaks and all optional/up for debate - would also be happy enough to approve in it's current form and loop back to making some tweaks once we have more tests written.

2020-12-08 12:20 UTC, martinmcneela commented on cypress/integration/common/common.js
> +  cy.wait(2000);
I don't think this is needed, I just ran test without and it all works.

2020-12-08 12:20 UTC, martinmcneela commented on cypress/integration/common/common.js
> +When(`I go from {string} to {string}`, (freeLayer, paidLayer) => {
```suggestion
When(`I go from {string} map layer to {string} map layer`, (freeLayer, paidLayer) => {
```

2020-12-08 12:20 UTC, martinmcneela commented on cypress/integration/common/common.js
> +  cy.get(`.ol-viewport`).click(100, 100);
At some point in the future I might set this to find the centre of the map to ensure there is always data there as it is now a common step, just noting here - no action needed.

2020-12-08 12:20 UTC, martinmcneela commented on cypress/integration/common/common.js
> +Then("The polygon is added to the map", async () => {
```suggestion
Then("The auto-polygon is added to the map", async () => {
```

2020-12-08 12:20 UTC, martinmcneela commented on cypress/integration/common/common.js
> +And(`I generate the maps and see {string}`, (address) => {
```suggestion
And(`I generate the maps and see {string} in the list of purchased map`, (address) => {
```

2020-12-08 12:20 UTC, martinmcneela commented on cypress/integration/AutomatedAreaTextBox/AutomatedAreaTextBox.js
> +And(`I agree to VOMM pricing`, () => {
```suggestion
And(`I agree to {string} modal`, () => {
```

2020-12-08 12:20 UTC, martinmcneela commented on cypress/integration/AutomatedAreaTextBox/AutomatedAreaTextBox.js
> +And(`I agree to VOMM pricing`, () => {
Just thinking if we do the above it can become a common step for accepting modals

2020-12-08 12:20 UTC, martinmcneela commented on cypress/integration/AutomatedAreaTextBox/AutomatedAreaTextBox.js
> +And(`I see the unique name of my test map on the my maps page`, () => {
Is this potentially a duplicate of line 62 in the common folder? As in they could be made in to one common step?

2020-12-11 11:01 UTC, wiled commented on cypress/integration/AutomatedAreaTextBox/AutomatedAreaTextBox.js
> +And(`I see the unique name of my test map on the my maps page`, () => {
Yeah, it's basically the same but this one uses the auto generated name from the code.  The feature doesn't know about it so it can't be a parameter.

2020-12-11 11:55 UTC, wiled commented on cypress/integration/AutomatedAreaTextBox.feature
> +    And I create a text box with the text 'Hello Wembley'
Have added the other auto text to this one too

2020-12-14 11:25 UTC, zac-robinson requested changes

2020-12-14 11:25 UTC, zac-robinson commented on cypress/integration/AutomatedAreaTextBox.feature
> +    When I click to select 'autoPolygon' drawing tool
Does this need this step? This test doesn't care about the autopolygon right?

2020-12-14 11:32 UTC, wiled commented on cypress/integration/AutomatedAreaTextBox.feature
> +    When I click to select 'autoPolygon' drawing tool
The test adds one to the map and edits the text for it, as well as the other automated text box

2020-12-15 09:34 UTC, zac-robinson approved these changes

2020-12-15 19:07 UTC, martinmcneela approved these changes

2020-12-16 09:30 UTC, merged