Scenario4
edozo/cypress_tests pull request #4
Opened 2020-12-15 14:44 UTC by Hazz223

First attempt at adding the fourth scenario as outlined [here](https://edozohq.atlassian.net/wiki/spaces/DEV/pages/1494712321/Maps+BDD+Tests#Scenario-4---Edit-a-Draft-Map).
I've got it updating the map information, and adding a rectangle. However, testing the tiles turned out to be a total mess.
Using [Cypress 6](https://docs.cypress.io/guides/references/changelog.html#6-0-0) and it's `intercept` concept, but couldn't get it to line up nicely, and looking at the test it looked incredibly brittle. 
Happy to discuss.

Also I updated to cypress 6 - I can remove this from this pr / submit a new pr that includes updates to other files to handle the now deprecated `.server()` calls etc.

2020-12-15 14:45 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +  cy.loginByApi()
Instead of going via the frontend, I instead submit a new map, and then open it for editing. It makes it much less "flaky", but means it won't follow what a user would _actually_ do. 
Also, if there's a better place for me to be storing this data, maybe with something like a `fixture` please let me know!

2020-12-15 19:38 UTC, martinmcneela requested changes
@Hazz223 bunch of comments, some are just musings and all are open for discussion 🙂 Also happy to hop on a call to discuss if you like. @wiled mentioned that maybe we can review them once everyone has done some and make some decisions on how to tackle certain things so  none of the change here are really necessary.

2020-12-15 19:38 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
> +  cy.loginByApi()
I don't really mind this @Hazz223 it is probably not needed for us to be testing the login for every test anyway. Maybe we should have one that tests the login form, and the rest of the tests use this method.

2020-12-15 19:38 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
> +        body: {
Would it be worth putting the body json block into a json file, or at lear export from its own javascript file? Will reduce noise in the main test file and may be a good pattern to have as some of the requests may be reused across tests.

2020-12-15 19:38 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
> +  cy.findByTestId("rectangle", { timeout: 5000 }).click();
Pretty sure the timeout is not needed here, mine works without it.

2020-12-15 19:38 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
> +  cy.findByTestId("mapNameInput").click().type("This is an edit to the name");
Is it worth typing a random name (like @wiled did in his PR https://github.com/edozo/cypress_tests/pull/3/files#diff-d653388b9d480b412841fd434e036525ef1732c253d57ae8a682a91b70bd4941R6) to make it a little more robust.

2020-12-15 19:38 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
> +When("I edit a map", () => {
Is it worth breaking the steps down into different `And` blocks with the strings driven by the .feature file and moving them into common as we will probably be reusing them?

2020-12-15 19:38 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
> +    .findByTestId("editButton", { timeout: 50000 })
Rather than an arbitrary timeout is there a way we can have cypress watch the able for an update?

2020-12-16 08:48 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +        body: {
Wasn't sure what the "standard" is with this sort of thing, so will go ahead and extract this 👍

2020-12-16 08:48 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +  cy.findByTestId("rectangle", { timeout: 5000 }).click();
Will remove

2020-12-16 08:51 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +When("I edit a map", () => {
I was thinking this as writing it - wasn't sure what the plan was to be around reuse, as it seems to be a real mix at the moment. I'll break these down in this file, ready to be moved into `common` as and when.

2020-12-16 08:54 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +    .findByTestId("editButton", { timeout: 50000 })
Ah, you reminded me of this, that I breezed past yesterday without thinking - [polling with cypress](https://docs.cypress.io/api/commands/request.html#Request-Polling) - I'll add this in, and create a condition that checks the status of the map we are interested in.

2020-12-16 10:00 UTC, wiled commented
IMO we should only be doing things that a user would be doing (so no direct API access to the backend) - having to click around on the UI to generate a map to be saved then edited would make a better test as it exercises the whole flow that a real user would make.  So using the UI login and UI to create the initial map (steps should exist for all of those already)

2020-12-16 10:25 UTC, Hazz223 commented
> IMO we should only be doing things that a user would be doing (so no direct API access to the backend) - having to click around on the UI to generate a map to be saved then edited would make a better test as it exercises the whole flow that a real user would make. So using the UI login and UI to create the initial map (steps should exist for all of those already)

I originally wrote it this way. I rewrote it using the api due to:
1. cypress recommends setting up data before you hit the page (according to @zac-robinson )
2. it was quite flaky
3. debugging was hard - if you have the browser console open can cause the data input to freak out, for example
4. test length was long

If they're planning to be a users interaction with the entire flow, maybe we should rewrite them not as multiple scenarios, but as a single test? So:
1. login
2. create map
3. create cad
4. check generated
5. edit map
6. and so on...
Thoughts / feelings?

2020-12-16 10:36 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
> +        body: {
I'm not sure of the 'standard' either @Hazz223, so not sure if my sugesttion is couter-productive.

2020-12-16 10:51 UTC, zac-robinson commented
From my perspective we should only be testing the part we actually care about I think. Testing UI login for every test is just duplication and adds places for flake and doesnt give us any more value in what the test provides

2020-12-16 11:42 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +    .findByTestId("editButton", { timeout: 50000 })
I've tried hooking in the above, but I kept hitting walls.
1. I tried to tie it into the `intercept` aspect, but that hit a brick wall as I think the single threaded nature of JS / this test caused it to lock
2. Managed to get it to repeatedly call, and check the body, but this would return "true, it's been generated" before the frontend would, as the frontend polls with explicit / back off timing. We'd have to sync this API checking code with the polling of the frontend to work correctly

As a result, I think waiting and checking that the `edit` button exists and is clickable is most like what the user will see. The above `wait` function will exit early if the button appears.

2020-12-16 12:05 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +When("I edit a map", () => {
Done

2020-12-16 12:05 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +  cy.findByTestId("mapNameInput").click().type("This is an edit to the name");
Done

2020-12-16 12:05 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +  cy.findByTestId("rectangle", { timeout: 5000 }).click();
Done

2020-12-16 12:06 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +        body: {
Moved it into a fixture. Seems like that is the standard, so will keep an eye out for it

2020-12-17 10:13 UTC, martinmcneela requested changes

2020-12-17 10:13 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
>    Given,
The `Before` here is not needed

2020-12-17 10:13 UTC, martinmcneela commented on cypress/integration/EditMap/EditMap.js
> +let description;
Pretty sure these don't need to be scoped outside their own block, so just `const` inside the `And` blocks should be ok.

2020-12-17 10:15 UTC, zac-robinson commented on cypress/integration/EditMap/EditMap.js
> +let description;
I don;t think cypress expects you to use variables at all in most cases

2020-12-18 14:08 UTC, Hazz223 commented on cypress/integration/EditMap/EditMap.js
> +let description;
Fixed this with @zac-robinson help - we've loaded this into `cy.wrap('some-data')` and can access it anywhere within the test structure. This should also enable some level of reuse.

2021-01-04 09:53 UTC, martinmcneela approved these changes

2021-01-04 11:54 UTC, zac-robinson approved these changes

2021-01-04 11:57 UTC, merged