Update to Cypress 6.2.1
edozo/cypress_tests pull request #5
Opened 2021-01-05 15:11 UTC by Hazz223

2021-01-12 12:07 UTC, Hazz223 commented on cypress/integration/AutomatedAreaTextBox.feature
> -    Then The auto-polygon is added to the map
I do not recall. I'll try adding it back to figure out why I removed it in the first place.

2021-01-12 13:37 UTC, Hazz223 commented on cypress/integration/AutomatedAreaTextBox.feature
> -    Then The auto-polygon is added to the map
I've added it back in. Not sure as to why it was removed in the first place?

2021-01-12 13:38 UTC, Hazz223 commented
I've updated this all, so I believe formatting should now be correct. Seems to run locally when using Firefox, but seems to have issues with Chrome _some_ of the time; seems to get stuck on the login page.

2021-01-12 17:27 UTC, martinmcneela submitted a review, later dismissed

2021-01-14 09:12 UTC, wiled requested changes

2021-01-14 09:12 UTC, wiled commented on cypress/integration/AutomatedAreaTextBox/AutomatedAreaTextBox.js
> +  cy.findByTestId('fontSizeInput').should('have.value', '3').clear().type(30);
moving all these statements onto a single line makes it much more difficult to follow

2021-01-14 09:12 UTC, wiled commented on cypress/integration/common/common.js
> +  cy.visit('https://dev-maps.edozo.co/', {
we should leave the URL factored out and change the step definition to not mention stage at all so we can more easily run it against different environments, this is moving it in the wrong direction

2021-01-14 09:33 UTC, Hazz223 commented on cypress/integration/common/common.js
> +  cy.visit('https://dev-maps.edozo.co/', {
Happy to move the URL back out of the function. However, I feel going through the code and updating the `I open stage` calls is out of scope for this ticket.

2021-01-14 09:34 UTC, Hazz223 commented on cypress/integration/AutomatedAreaTextBox/AutomatedAreaTextBox.js
> +  cy.findByTestId('fontSizeInput').should('have.value', '3').clear().type(30);
I asked @martinmcneela and @zac-robinson around formatting, and installed the plugins required. I'll deferrer to them around styling. Thoughts @zac-robinson @martinmcneela

2021-01-14 09:35 UTC, Hazz223 commented on cypress/integration/common/common.js
> +  cy.visit('https://dev-maps.edozo.co/', {
Actually, looking at it, it's pretty easy. Screw it, I'll fix it up.

2021-01-14 09:47 UTC, Hazz223 commented on cypress/integration/common/common.js
> +  cy.visit('https://dev-maps.edozo.co/', {
Done

2021-01-14 10:05 UTC, martinmcneela commented on cypress/integration/AutomatedAreaTextBox/AutomatedAreaTextBox.js
> +  cy.findByTestId('fontSizeInput').should('have.value', '3').clear().type(30);
Valid point @wiled, but I think it comes down to preference and concistency. For me for example, I find the one line version easier to read and cleaner when sitting in a file, but it will break to multiple lines once there are more than 120 characters on that line. This also follows along with what we use in maps, admin...etc... as we are trying to keep the javascript code concistent across apps.

We could add a rule specifically for braking to a newline per chained call (https://eslint.org/docs/rules/newline-per-chained-call)? I guess it falls on the concensus of the team members who will be writing the tests.

@zac-robinson what do you think on this? And @Hazz223 which makes it easier for you to follow?

2021-01-14 10:20 UTC, wiled approved these changes

2021-01-14 10:20 UTC, wiled commented on cypress/integration/AutomatedAreaTextBox.feature
> +    Given I open maps
nice

2021-01-14 10:31 UTC, Hazz223 commented on cypress/integration/AutomatedAreaTextBox/AutomatedAreaTextBox.js
> +  cy.findByTestId('fontSizeInput').should('have.value', '3').clear().type(30);
New lined items follow a more functional style, though I'd argue this isn't really functional. 
I personally don't mind either way, but I do mind about consistency. Have different styles littering the code base makes it difficult for juniors like me to learn / understand what is the "correct" way to structure the JS I'm writing. 
So whatever is picked, I'd like it to be seen everywhere in the code at least within the project.

2021-01-14 11:58 UTC, martinmcneela commented on cypress/integration/AutomatedAreaTextBox/AutomatedAreaTextBox.js
> +  cy.findByTestId('fontSizeInput').should('have.value', '3').clear().type(30);
So if we added the eslint rule fromt he last comment it would keep this project concistent, it would just differ from the others. Which I guess would be ok ans it is more cross-team?

2021-01-14 11:58 UTC, martinmcneela approved these changes

2021-01-14 12:40 UTC, wiled commented on cypress/integration/AutomatedAreaTextBox/AutomatedAreaTextBox.js
> +  cy.findByTestId('fontSizeInput').should('have.value', '3').clear().type(30);
If everyone else but me is ok with it on one line then better do it that way and I'll just have to live with it :D

I just find it easier to rapidly parse when it's in a more functional style but I do favour consistency and seems this is effectively a break from that

2021-01-14 13:21 UTC, merged