MAPS-900: add scenario 5
edozo/cypress_tests pull request #6
Opened 2021-01-14 14:29 UTC by wiled

2021-01-18 17:59 UTC, martinmcneela requested changes

2021-01-18 17:59 UTC, martinmcneela commented on cypress/integration/common/common.js
> +  cy.get('.ol-viewport')
Would it be possible to make the rectangle larger, so it is visible on the map to the eye as well as programmatically? Probably not a massive deal, I was just wondering why the test was passing when the polygon wasn't there.

2021-01-18 17:59 UTC, martinmcneela commented on cypress/integration/common/common.js
> +  var height = cy.get('.ol-viewport').its('height');
Can these be `const` for consistency

2021-01-18 17:59 UTC, martinmcneela commented on cypress/integration/EditShape/EditShape.js
> +import { When, And, Then, Given } from "cypress-cucumber-preprocessor/steps";
- `Given` doesn't need to be imported here as it isn't used.
- The formatting of the file doesn't follow the rules ZR and HHH added, admittedly the rules do need tweaked.

Out of curiosity do you use VSCode for these tests or InteliJ?

2021-01-18 17:59 UTC, martinmcneela commented on cypress/integration/EditShape/EditShape.js
> +Then('Only one {int} point shape should be sent to the backend in the preview request', (points) => {
`points` shouldn't be passed as an argument on this line as it is not used.

2021-01-19 08:40 UTC, wiled commented on cypress/integration/common/common.js
> +  cy.get('.ol-viewport')
This should be a rectangle with a point at the centre and the opposite point near a corner (width/1.1 + height/1.1) - a point has to be at the centre otherwise I can't reliabily click on it to remove it after reloading the map

2021-01-19 08:41 UTC, wiled commented on cypress/integration/EditShape/EditShape.js
> +import { When, And, Then, Given } from "cypress-cucumber-preprocessor/steps";
I'm using intellij

2021-01-19 08:42 UTC, wiled commented on cypress/integration/EditShape/EditShape.js
> +Then('Only one {int} point shape should be sent to the backend in the preview request', (points) => {
Changed it to use the param

2021-01-19 08:50 UTC, wiled commented on cypress/integration/common/common.js
> +  cy.get('.ol-viewport')
This creates a rectangle that is 1/4 of the viewport

2021-01-25 18:55 UTC, martinmcneela commented on cypress/integration/EditShape/EditShape.js
> +import { When, And, Then, Given } from "cypress-cucumber-preprocessor/steps";
ok cool. I think at some point we will be enforcing the linting stuff on commit to make sure the project is concistent, but also given it is a JS project VSCode might be a better option anyway. Happy to helpget it all setup if you need it.

2021-01-25 19:06 UTC, martinmcneela commented on cypress/integration/common/common.js
> +  cy.get('.ol-viewport')
It might be getting the width and height before the vieport is ready, but when I run it I can't see a polygon on the map and when I try to view that map in edit there is a tiny polygon in the center of the map.

2021-01-25 19:11 UTC, martinmcneela commented on cypress/integration/EditShape/EditShape.js
> +Then('Only one {int} point shape should be sent to the backend in the preview request', (points) => {
Ok cool, does the .Feature file need to have single quotes around the 3 for this to work? I would check but nothing is generating for me at the min.

2021-01-25 19:11 UTC, martinmcneela requested changes
Answered a couple of comments

2021-01-26 09:15 UTC, wiled commented on cypress/integration/EditShape/EditShape.js
> +Then('Only one {int} point shape should be sent to the backend in the preview request', (points) => {
No, quotes not needed for ints

2021-01-26 14:52 UTC, martinmcneela approved these changes

2021-01-27 17:43 UTC, martinmcneela submitted a review, later dismissed

2021-01-29 09:30 UTC, zac-robinson approved these changes

2021-01-29 09:32 UTC, martinmcneela approved these changes

2021-01-29 09:34 UTC, merged